# Generated by Django 3.2 on 2022-01-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rope_size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
