# Generated by Django 3.2 on 2022-01-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_rope_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rope_size',
            new_name='rope_size_option',
        ),
    ]
